# Generated by Django 4.2.28 on 2026-02-27 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('media_type', models.CharField(choices=[('film', 'Film'), ('tv', 'Television'), ('both', 'Film & TV')], default='both', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('year_of_study', models.CharField(blank=True, max_length=50)),
                ('university', models.CharField(blank=True, max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('article_type', models.CharField(choices=[('review', 'Review'), ('essay', 'Essay'), ('interview', 'Interview'), ('list', 'List')], default='review', max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('cover_image_url', models.URLField(blank=True, help_text='Or paste an image URL instead of uploading')),
                ('excerpt', models.TextField(help_text='Short summary shown on listing pages', max_length=400)),
                ('body', models.TextField()),
                ('subject_title', models.CharField(blank=True, help_text='Name of the film/show being discussed', max_length=255)),
                ('subject_year', models.CharField(blank=True, help_text='Release year', max_length=10)),
                ('director', models.CharField(blank=True, help_text='Director/Creator name', max_length=255)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Rating out of 10', max_digits=3, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.category')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
